server:
  port: 8083

spring:
  datasource:
    #url: jdbc:mysql://${DB_HOST:http://localhost:3306}/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    url: ${DB_HOST}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #validate
  application:
    name: AUTH-SERVICE

jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
